// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApzE1re1KB9sA_SyJUrm2UR8xqWaJJotU',
    appId: '1:469878673090:web:c44287f548ac8a0aabf55b',
    messagingSenderId: '469878673090',
    projectId: 'finance-tracker-9ba02',
    authDomain: 'finance-tracker-9ba02.firebaseapp.com',
    storageBucket: 'finance-tracker-9ba02.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaxLS3LY5JnTpsYzkAEh1g3On4C-Ag42Y',
    appId: '1:469878673090:android:5ae6bfefd500555babf55b',
    messagingSenderId: '469878673090',
    projectId: 'finance-tracker-9ba02',
    storageBucket: 'finance-tracker-9ba02.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXq7Wk6-mv9GQ59154XieT9l5LDZLB1ag',
    appId: '1:469878673090:ios:d53c38ea2e0a8d34abf55b',
    messagingSenderId: '469878673090',
    projectId: 'finance-tracker-9ba02',
    storageBucket: 'finance-tracker-9ba02.firebasestorage.app',
    iosBundleId: 'com.example.financeTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApzE1re1KB9sA_SyJUrm2UR8xqWaJJotU',
    appId: '1:469878673090:web:daae759905baf2e1abf55b',
    messagingSenderId: '469878673090',
    projectId: 'finance-tracker-9ba02',
    authDomain: 'finance-tracker-9ba02.firebaseapp.com',
    storageBucket: 'finance-tracker-9ba02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXq7Wk6-mv9GQ59154XieT9l5LDZLB1ag',
    appId: '1:469878673090:ios:d53c38ea2e0a8d34abf55b',
    messagingSenderId: '469878673090',
    projectId: 'finance-tracker-9ba02',
    storageBucket: 'finance-tracker-9ba02.firebasestorage.app',
    iosBundleId: 'com.example.financeTracker',
  );

}